image: node:alpine
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.npm
stages:
  - test
  - deploy
expo-deployments:
  stage: deploy
  script:
    - apk add --no-cache --virtual .gyp python make g++ bash
    - npm install
    - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - npx expo publish --non-interactive
    - apk del .gyp