image: node:slim
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.npm
    - .jest
stages:
  - deploy  
expo-deployments:
  stage: deploy
  script:
    - apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
    - npm i
    - echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
    - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD --non-interactive
    - npx expo publish --non-interactive
  only:
    - master
    - devel
