version: '3'

services:
  mobile:
    container_name: mobile
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19006:19006
    network_mode: host