version: '3'

services:
  mobile:
    container_name: mobile
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19006:19006
    network_mode: host
  
  authentication_app:
    image: registry.gitlab.com/fastpay-pi2/authentication-api/app:latest
    depends_on:
      - authentication_db
    networks:
      - fastpay
      - auth
    ports:
      - '3001:3001'

  authentication_db:
    image: mongo
    networks:
      - auth
    ports:
      - 27017:27017

  products_api:
    image: registry.gitlab.com/fastpay-pi2/products-api/app:latest
    env_file:
      - .env
    depends_on:
      - products_db
    networks:
      - fastpay
      - products
    ports:
      - "3000:3000"

  products_db:
    image: registry.gitlab.com/fastpay-pi2/products-api/db:latest
    networks:
      - products
    env_file:
      - .env
    ports:
      - "5432:5432"

networks:
  fastpay:
  auth:
  products:
